// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMQBrokerInstallationPlanInput) DeepCopyInto(out *AMQBrokerInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMQBrokerInstallationPlanInput.
func (in *AMQBrokerInstallationPlanInput) DeepCopy() *AMQBrokerInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(AMQBrokerInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMQInterconnectInstallationPlanInput) DeepCopyInto(out *AMQInterconnectInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMQInterconnectInstallationPlanInput.
func (in *AMQInterconnectInstallationPlanInput) DeepCopy() *AMQInterconnectInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(AMQInterconnectInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMQStreamsInstallationPlanInput) DeepCopyInto(out *AMQStreamsInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMQStreamsInstallationPlanInput.
func (in *AMQStreamsInstallationPlanInput) DeepCopy() *AMQStreamsInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(AMQStreamsInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDesignerInstallationPlanInput) DeepCopyInto(out *APIDesignerInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDesignerInstallationPlanInput.
func (in *APIDesignerInstallationPlanInput) DeepCopy() *APIDesignerInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(APIDesignerInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CamelKInstallationPlanInput) DeepCopyInto(out *CamelKInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CamelKInstallationPlanInput.
func (in *CamelKInstallationPlanInput) DeepCopy() *CamelKInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(CamelKInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FuseConsoleInstallationPlanInput) DeepCopyInto(out *FuseConsoleInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FuseConsoleInstallationPlanInput.
func (in *FuseConsoleInstallationPlanInput) DeepCopy() *FuseConsoleInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(FuseConsoleInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FuseOnlineInstallationPlanInput) DeepCopyInto(out *FuseOnlineInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FuseOnlineInstallationPlanInput.
func (in *FuseOnlineInstallationPlanInput) DeepCopy() *FuseOnlineInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(FuseOnlineInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Installation) DeepCopyInto(out *Installation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Installation.
func (in *Installation) DeepCopy() *Installation {
	if in == nil {
		return nil
	}
	out := new(Installation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Installation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationList) DeepCopyInto(out *InstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Installation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationList.
func (in *InstallationList) DeepCopy() *InstallationList {
	if in == nil {
		return nil
	}
	out := new(InstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationPlan) DeepCopyInto(out *InstallationPlan) {
	*out = *in
	out.InstallationPlanBase = in.InstallationPlanBase
	out.InstallationPlanInput = in.InstallationPlanInput
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationPlan.
func (in *InstallationPlan) DeepCopy() *InstallationPlan {
	if in == nil {
		return nil
	}
	out := new(InstallationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationPlanBase) DeepCopyInto(out *InstallationPlanBase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationPlanBase.
func (in *InstallationPlanBase) DeepCopy() *InstallationPlanBase {
	if in == nil {
		return nil
	}
	out := new(InstallationPlanBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationPlanInput) DeepCopyInto(out *InstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationPlanInput.
func (in *InstallationPlanInput) DeepCopy() *InstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(InstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationSpec) DeepCopyInto(out *InstallationSpec) {
	*out = *in
	if in.ThreeScaleInstallationPlanInput != nil {
		in, out := &in.ThreeScaleInstallationPlanInput, &out.ThreeScaleInstallationPlanInput
		*out = new(ThreeScaleInstallationPlanInput)
		**out = **in
	}
	if in.ThreeScaleAPIcastInstallationPlanInput != nil {
		in, out := &in.ThreeScaleAPIcastInstallationPlanInput, &out.ThreeScaleAPIcastInstallationPlanInput
		*out = new(ThreeScaleAPIcastInstallationPlanInput)
		**out = **in
	}
	if in.AMQBrokerInstallationPlanInput != nil {
		in, out := &in.AMQBrokerInstallationPlanInput, &out.AMQBrokerInstallationPlanInput
		*out = new(AMQBrokerInstallationPlanInput)
		**out = **in
	}
	if in.AMQInterconnectInstallationPlanInput != nil {
		in, out := &in.AMQInterconnectInstallationPlanInput, &out.AMQInterconnectInstallationPlanInput
		*out = new(AMQInterconnectInstallationPlanInput)
		**out = **in
	}
	if in.AMQStreamsInstallationPlanInput != nil {
		in, out := &in.AMQStreamsInstallationPlanInput, &out.AMQStreamsInstallationPlanInput
		*out = new(AMQStreamsInstallationPlanInput)
		**out = **in
	}
	if in.APIDesignerInstallationPlanInput != nil {
		in, out := &in.APIDesignerInstallationPlanInput, &out.APIDesignerInstallationPlanInput
		*out = new(APIDesignerInstallationPlanInput)
		**out = **in
	}
	if in.CamelKInstallationPlanInput != nil {
		in, out := &in.CamelKInstallationPlanInput, &out.CamelKInstallationPlanInput
		*out = new(CamelKInstallationPlanInput)
		**out = **in
	}
	if in.FuseConsoleInstallationPlanInput != nil {
		in, out := &in.FuseConsoleInstallationPlanInput, &out.FuseConsoleInstallationPlanInput
		*out = new(FuseConsoleInstallationPlanInput)
		**out = **in
	}
	if in.FuseOnlineInstallationPlanInput != nil {
		in, out := &in.FuseOnlineInstallationPlanInput, &out.FuseOnlineInstallationPlanInput
		*out = new(FuseOnlineInstallationPlanInput)
		**out = **in
	}
	if in.ServiceRegistryInstallationPlanInput != nil {
		in, out := &in.ServiceRegistryInstallationPlanInput, &out.ServiceRegistryInstallationPlanInput
		*out = new(ServiceRegistryInstallationPlanInput)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationSpec.
func (in *InstallationSpec) DeepCopy() *InstallationSpec {
	if in == nil {
		return nil
	}
	out := new(InstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationStatus) DeepCopyInto(out *InstallationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationStatus.
func (in *InstallationStatus) DeepCopy() *InstallationStatus {
	if in == nil {
		return nil
	}
	out := new(InstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistryInstallationPlanInput) DeepCopyInto(out *ServiceRegistryInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistryInstallationPlanInput.
func (in *ServiceRegistryInstallationPlanInput) DeepCopy() *ServiceRegistryInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistryInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleAPIcastInstallationPlanInput) DeepCopyInto(out *ThreeScaleAPIcastInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleAPIcastInstallationPlanInput.
func (in *ThreeScaleAPIcastInstallationPlanInput) DeepCopy() *ThreeScaleAPIcastInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleAPIcastInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleInstallationPlanInput) DeepCopyInto(out *ThreeScaleInstallationPlanInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleInstallationPlanInput.
func (in *ThreeScaleInstallationPlanInput) DeepCopy() *ThreeScaleInstallationPlanInput {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleInstallationPlanInput)
	in.DeepCopyInto(out)
	return out
}
