// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMQBrokerInstallationInputFields) DeepCopyInto(out *AMQBrokerInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMQBrokerInstallationInputFields.
func (in *AMQBrokerInstallationInputFields) DeepCopy() *AMQBrokerInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(AMQBrokerInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMQInterconnectInstallationInputFields) DeepCopyInto(out *AMQInterconnectInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMQInterconnectInstallationInputFields.
func (in *AMQInterconnectInstallationInputFields) DeepCopy() *AMQInterconnectInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(AMQInterconnectInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMQStreamsInstallationInputFields) DeepCopyInto(out *AMQStreamsInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMQStreamsInstallationInputFields.
func (in *AMQStreamsInstallationInputFields) DeepCopy() *AMQStreamsInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(AMQStreamsInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDesignerInstallationInputFields) DeepCopyInto(out *APIDesignerInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDesignerInstallationInputFields.
func (in *APIDesignerInstallationInputFields) DeepCopy() *APIDesignerInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(APIDesignerInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CamelKInstallationInputFields) DeepCopyInto(out *CamelKInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CamelKInstallationInputFields.
func (in *CamelKInstallationInputFields) DeepCopy() *CamelKInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(CamelKInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FuseConsoleInstallationInputFields) DeepCopyInto(out *FuseConsoleInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FuseConsoleInstallationInputFields.
func (in *FuseConsoleInstallationInputFields) DeepCopy() *FuseConsoleInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(FuseConsoleInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FuseOnlineInstallationInputFields) DeepCopyInto(out *FuseOnlineInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FuseOnlineInstallationInputFields.
func (in *FuseOnlineInstallationInputFields) DeepCopy() *FuseOnlineInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(FuseOnlineInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Installation) DeepCopyInto(out *Installation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Installation.
func (in *Installation) DeepCopy() *Installation {
	if in == nil {
		return nil
	}
	out := new(Installation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Installation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationInputFields) DeepCopyInto(out *InstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationInputFields.
func (in *InstallationInputFields) DeepCopy() *InstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(InstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationList) DeepCopyInto(out *InstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Installation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationList.
func (in *InstallationList) DeepCopy() *InstallationList {
	if in == nil {
		return nil
	}
	out := new(InstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationPlan) DeepCopyInto(out *InstallationPlan) {
	*out = *in
	out.InstallationInputFields = in.InstallationInputFields
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationPlan.
func (in *InstallationPlan) DeepCopy() *InstallationPlan {
	if in == nil {
		return nil
	}
	out := new(InstallationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationSpec) DeepCopyInto(out *InstallationSpec) {
	*out = *in
	out.ThreeScaleInstallationInputFields = in.ThreeScaleInstallationInputFields
	out.ThreeScaleAPIcastInstallationInputFields = in.ThreeScaleAPIcastInstallationInputFields
	out.AMQBrokerInstallationInputFields = in.AMQBrokerInstallationInputFields
	out.AMQInterconnectInstallationInputFields = in.AMQInterconnectInstallationInputFields
	out.AMQStreamsInstallationInputFields = in.AMQStreamsInstallationInputFields
	out.APIDesignerInstallationInputFields = in.APIDesignerInstallationInputFields
	out.CamelKInstallationInputFields = in.CamelKInstallationInputFields
	out.FuseConsoleInstallationInputFields = in.FuseConsoleInstallationInputFields
	out.FuseOnlineInstallationInputFields = in.FuseOnlineInstallationInputFields
	out.ServiceRegistryInstallationInputFields = in.ServiceRegistryInstallationInputFields
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationSpec.
func (in *InstallationSpec) DeepCopy() *InstallationSpec {
	if in == nil {
		return nil
	}
	out := new(InstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationStatus) DeepCopyInto(out *InstallationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationStatus.
func (in *InstallationStatus) DeepCopy() *InstallationStatus {
	if in == nil {
		return nil
	}
	out := new(InstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRegistryInstallationInputFields) DeepCopyInto(out *ServiceRegistryInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRegistryInstallationInputFields.
func (in *ServiceRegistryInstallationInputFields) DeepCopy() *ServiceRegistryInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(ServiceRegistryInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleAPIcastInstallationInputFields) DeepCopyInto(out *ThreeScaleAPIcastInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleAPIcastInstallationInputFields.
func (in *ThreeScaleAPIcastInstallationInputFields) DeepCopy() *ThreeScaleAPIcastInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleAPIcastInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleInstallationInputFields) DeepCopyInto(out *ThreeScaleInstallationInputFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleInstallationInputFields.
func (in *ThreeScaleInstallationInputFields) DeepCopy() *ThreeScaleInstallationInputFields {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleInstallationInputFields)
	in.DeepCopyInto(out)
	return out
}
